apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gqof
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-gqof@sha256:c36132384f2cd67a1caf4136ac3c974d4a128ab43f6a467d503bc4da0056349c
        name: my-nodejs
        resources: {}
status: {}
